extends Node
## AudioManager (autoload) — plays themed music + sound effects.
## FAIL-SOFT: a missing/unimported audio file simply stays silent; the game must
## never crash over audio (it's a kids' app that has to keep running).
## Respects the local SaveManager.settings music/sfx toggles. No network, ever.

const POOL_SIZE := 8

var _music: AudioStreamPlayer
var _sfx_pool: Array[AudioStreamPlayer] = []
var _next: int = 0
var _cache: Dictionary = {}        # path -> AudioStream (or null if absent)

func _ready() -> void:
	_music = AudioStreamPlayer.new()
	add_child(_music)
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_sfx_pool.append(p)
	# Auto-react to gameplay so callers don't have to wire every sound by hand.
	GameCore.run_started.connect(play_music)
	GameCore.critter_rescued.connect(_on_rescued)
	GameCore.stumbled.connect(func(_lives): play_sfx("miss"))
	GameCore.paused_changed.connect(set_paused)

func set_paused(is_paused: bool) -> void:
	_music.stream_paused = is_paused

func _on_rescued(_id: String, _total: int) -> void:
	# Pitch climbs with the streak so a hot run literally sounds more exciting.
	play_sfx("rescue", 1.0 + minf(GameCore.streak, 8) * 0.04)

func play_sfx(sound: String, pitch: float = 1.0) -> void:
	if not bool(SaveManager.settings.get("sfx", true)):
		return
	var stream := _load(ThemeManager.audio(sound))
	if stream == null:
		return
	var p := _sfx_pool[_next]
	_next = (_next + 1) % POOL_SIZE
	p.stream = stream
	p.pitch_scale = pitch
	p.play()

func play_music() -> void:
	if not bool(SaveManager.settings.get("music", true)):
		return
	var stream := _load(ThemeManager.audio("music"))
	if stream == null:
		return
	if stream is AudioStreamOggVorbis:
		stream.loop = true
	elif stream is AudioStreamWAV:
		# Placeholder WAV loops (generated by tools/gen_placeholder_audio.py).
		stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
		stream.loop_begin = 0
		stream.loop_end = stream.data.size() / 2   # 16-bit mono: 2 bytes/frame
	_music.stream = stream
	if not _music.playing:
		_music.play()

func stop_music() -> void:
	_music.stop()

func _load(path: String) -> AudioStream:
	if path == "":
		return null
	if _cache.has(path):
		return _cache[path]
	var stream: AudioStream = null
	if ResourceLoader.exists(path):
		stream = ResourceLoader.load(path) as AudioStream
	else:
		# Placeholder convention: a generated .wav may stand in for a not-yet-
		# sourced .ogg at the same theme.json path. Real .ogg wins once present.
		var alt := path.get_basename() + ".wav"
		if alt != path and ResourceLoader.exists(alt):
			stream = ResourceLoader.load(alt) as AudioStream
		else:
			push_warning("AudioManager: audio not found (silent): %s" % path)
	_cache[path] = stream
	return stream
